In [1]:
import numpy as np

a = np.random.uniform(1, 20, 20)  # creating the random vector of size 20 having only float in the range 1-20
print('Random vector of size  20: \n', a)
b = a.reshape((4, 5))  # reshaping the array to 4 by 5
print('Reshaping the  array to 4 by 5: \n', b)
c = np.where(b == np.amax(b, axis=1).reshape(-1, 1), 0, b)  # replace the max in each row by 0(axis=1)
print('Replacing the  maximum in each row by 0: \n', c)

Random vector of size  20: 
 [ 2.58481544 19.72238768 13.9110957  19.01501862  3.02672526  1.80203033
 13.32879332  1.19429777 13.29209105 15.27395143 12.97588385  5.86871662
 19.35196209  5.0734041  17.37880586 13.00176082  7.3028859  10.67669637
 15.84830229 17.37011009]
Reshaping the  array to 4 by 5: 
 [[ 2.58481544 19.72238768 13.9110957  19.01501862  3.02672526]
 [ 1.80203033 13.32879332  1.19429777 13.29209105 15.27395143]
 [12.97588385  5.86871662 19.35196209  5.0734041  17.37880586]
 [13.00176082  7.3028859  10.67669637 15.84830229 17.37011009]]
Replacing the  maximum in each row by 0: 
 [[ 2.58481544  0.         13.9110957  19.01501862  3.02672526]
 [ 1.80203033 13.32879332  1.19429777 13.29209105  0.        ]
 [12.97588385  5.86871662  0.          5.0734041  17.37880586]
 [13.00176082  7.3028859  10.67669637 15.84830229  0.        ]]


In [22]:
class Employee:
    """
    Generic Employee class with name, family, salary and department
    """

    # data member to count the number of Employees
    no_of_employees = 0

    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1

    @staticmethod
    def average_salary(employees):
        """
        function to average salary
        """
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees


class FulltimeEmployee(Employee):
    """
    Full Time Employee is a sub class of Employee
    """

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_benefits(self):
        print("Few benefits as full time employee.")


def main():
    employees = []
    fte1 = FulltimeEmployee("Abhya Ram", "Nandamuri", 45000000, "Doctor")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("Van", "Jampani", 6780000, "HR")
    employees.append(fte2)
    emp1 = Employee("Bhagi", "Palaparthi", 4560000, "PHD")
    employees.append(emp1)
    emp2 = Employee("Geetu", "Doddapaneni", 236000, "Rnd")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()

Few benefits as full time employee.
Average salary: 14144000.0
